### PR TITLE
add measuring path directly (for spells etc), fixes #138

### LINKED ISSUE #138: Allow Measuring in straight line

### PR DESCRIPTION
**Pull request by corinnaj**

### CODE REVIEW

**Comment by cmfcmf** [comment]
The code looks good 👍

I have thought about the feature itself a bit more as well. Here are my thoughts:
I think measurement can be separated into two things:
1. How we display the measure path
2. How we calculate distances

For 1, I think it would make sense to always just show a straight line when using the measure tool, regardless of how we calculate the distance. While I think that it makes a lot of sense to use lots of small line segments when moving a token, I think it doesn't really make sense when using the measure tool.

For 2, I think we should generally keep using the "every second diagonal square counts as two squares" method we also use for token movement. It would be odd when the distance measured with the measure tool does not match up with the distance of moving a token.
However, it might make sense to keep the extra "direct" measure tool option - maybe we'll need it in the future (e.g., when/if we better support playing without a grid) or there is a use case I am simply not seeing at the moment. Perhaps it would make sense to _not_ floor it to 5 feet increments, but to 1 feet increments, so that it is even clearer that this is the exact distance?

**Comment by corinnaj** [comment]
I'm not sure I agree with 1. I also use the measuring tool for planning my movement before it's my turn, so I like having the option of seeing exactly which tiles I pass through. 
I use the measuring tool instead of the token movement there, because I don't want to "interrupt" the current state for the person who has their turn at the moment. (Also I tend to forget where exactly my token started, once I let go of it)

**Comment by corinnaj** [comment]
As for 2, I think both options would work for me. Both feel a bit strange if I think about it, but I think that's just the nature of trying to adapt everything to a grid.

**Comment by cmfcmf** [comment]
> I'm not sure I agree with 1. I also use the measuring tool for planning my movement before it's my turn, so I like having the option of seeing exactly which tiles I pass through.

Hmm, but the measure tool currently doesn't really allow you to do that, does it? E.g. I cannot plan my move correctly in this picture, since the measure path does not follow my mouse (like when moving a token), but simply takes one of the multiple shortest paths from the start to my mouse cursor.
image

**Comment by corinnaj** [comment]
Hm, so maybe we should change the original mode to always keep all tiles I visited (as the token movement does), while the other mode measures in straight lines?

**Comment by cmfcmf** [comment]
> Hm, so maybe we should change the original mode to always keep all tiles I visited (as the token movement does), while the other mode measures in straight lines?

Sounds great!

**Comment by corinnaj** [comment]
Should hopefully be working now :)

**Review by cmfcmf — APPROVED** [review]
Works great!

**Pull request merged**
